### ISSUE TITLE
Distribute on pypi or otherwise

### ISSUE THREAD

**Issue by johanneswilm** [rrthomas/rpl#8]
Hey,
I need to get the newest version of rpl (the one that can deal with recursive searches), but it's quite difficult to get it set up locally as long as Ubuntu is still distributing an older version. Could it not be uploaded to pypi or some other place?

**Comment by rrthomas** [comment]
I will look into this. In the mean time

```
python3 setup.py install --user
```

works for me, although it doesn't install the man page—I'll see if I can fix that too as a prelude to pypi.

**Comment by rrthomas** [comment]
I have fixed the installation of the man page.

**Comment by rrthomas** [comment]
I have improved the setup so that it works both for installation as normal, and packaging. I have uploaded a test project to test.pypi.org; when I tried to upload to pypi.org proper, I was refused the use of the name "rpl", so I've filed an issue: https://github.com/pypa/pypi-support/issues/649

Of course if this is refused, I can use another name.

**Comment by johanneswilm** [comment]
Thank you so much for your efforts so far. Let's hope they answer you soon.

**Comment by rrthomas** [comment]
Just to update this issue: I got a positive answer, including approval to use the name. I've just pinged the PyPI issue to ask how long it might take.

**Comment by rrthomas** [comment]
Finally the project name has been unlocked on PyPI, and I've uploaded rpl.
